[module]
module.name = "Numbers\Backend\SMS\Common"
module.code = "SM-SMS-Common"
module.title = "Common functionalities for SMS"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.System.Modules = 1
dep.submodule.Numbers.Backend.Db.__any = 1

; --- models (name and parent class) ---
dep.model.\Numbers\Backend\SMS\Common\Model\Profiles = "\Object\Table"
dep.model.\Numbers\Backend\SMS\Common\Model\Profile\Senders = "\Object\Table"

dep.model.\Numbers\Backend\SMS\Common\Data\System = "\Object\Import"

[help]
; This module has common tables, imports and reports