[module]
module.name = "Numbers\Backend\Configuration\Db"
module.code = "SM-Configuration-Db"
module.title = "Configuration Db"
module.version = "1.0.0"

[dependencies]

; --- models (name and parent class) ---
dep.model.\Numbers\Backend\Configuration\Db\Model\ConfigurationValues = "\Object\Table"

dep.model.\Numbers\Backend\Configuration\Db\Data\System = "\Object\Import"

[help]
; Configuration Db