[module]
module.name = "Numbers.Backend.Db.Extension.PostgreSQL.Vector"
module.code = "SM-PostgreSQL-Vector"
module.title = "Vector for PostgreSQL"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.Db.PostgreSQL = 1

; warnings
dep.extra_configs.warnings.Vector = "Make sure Postgres configuration exists: search_path = '\"$user\",public,extensions'"

; --- models (name and parent class) ---
dep.model.\Numbers\Backend\Db\Extension\PostgreSQL\Vector\Model\Vector = "\Object\Extension"

; grab import from system modules first
dep.model.\Numbers\Backend\Db\Extension\PostgreSQL\Vector\Data\Import = "\Object\Import"

[help]
; brew install pgvector