[module]
module.name = "Numbers\Backend\Configuration\Ini"
module.code = "SM-Configuration-Ini"
module.title = "Ini Configuration"
module.version = "1.0.0"

[dependencies]


[help]
; Ini Configuration