[module]
module.name = "Numbers\Backend\Configuration\Environment"
module.code = "SM-Configuration-Environment"
module.title = "Environment Configuration"
module.version = "1.0.0"

[dependencies]


[help]
; Environment Configuration