[module]
module.name = "Numbers/Backend/System/Concurrencies"
module.code = "SM-Concurrencies"
module.title = "System Concurrencies"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.System.Modules = 1

; APIs
dep.api.\Numbers\Backend\System\Concurrencies\API\V1\SM\ConcurrentCalls = "API"

[help]
; S/M System Concurrencies