[module]
module.name = "Numbers\Backend\Configuration\JSON"
module.code = "SM-Configuration-JSON"
module.title = "JSON Configuration"
module.version = "1.0.0"

[dependencies]


[help]
; JSON Configuration